### ISSUE TITLE
AWS Status Inventory

### ISSUE THREAD

**Issue by AlpacaFur** [sandboxnu/major-scraper#1]
## Summary
We want to get a better picture overall of what Graduate and Search's AWS stacks look like and how they fit together. We don't need to do a super deep dive on any component yet, but it'll be helpful to have a concrete high-level view.

## Tasks
- [ ] Review what our setup is at the moment in the AWS Console / Team Repos
    - Graduate’s Setup (frontend, backend, DB)
    - Search’s Setup (frontend, course-catalog-api, course-catalog-scraper, terraform, DB)
- [ ] Investigate if any of the AWS tools we're using have any built in downtime/restart alerting or if we need to choose another option/roll our own using an API
    - Search currently has an external downtime bot in their `#search-support` channel, we could probably set something similar up for Graduate if that seems like a good option
- [ ] Find out what error logging we have in place for Graduate's backend and Search's scraper/backend.
- [ ] Take note of anything you come across that you're unsure about/seems like it should be different.
- [ ] Write up these findings in a Notion Doc and informally present to interested people on the team.
