### ISSUE TITLE
Implement New Scraper Output Format

### ISSUE THREAD

**Issue by AlpacaFur** [sandboxnu/major-scraper#4]
- Blocks #5

## Summary
- Now that we landed on a good output format in #3, we should have the scraper output into that format.

## Tasks
- [ ] Based on the decisions in [this notion doc](https://www.notion.so/sandboxnu/The-Ultimate-Scraper-Docs-c9d9bba6e0cd4c46aa7742eaea2c1e67), implement this output format for the scraper.
- [ ] The scraper should output into the `../degrees/majors` directory by default, and should exit with an error if such a directory doesn't exist. This is where the [sandboxnu/degrees](https://github.com/sandboxnu/degrees) will be installed for scraper development, so we'd like to a folder called `majors` within that repo. (This will be made configurable in #5)

**Comment by clue4** [comment]
- [ ] update Major2 types to include metadata
- [ ] implement directory output (year >> school >> major)
- [ ] let's discuss file copies at standup tomorrow 10/4 -- manual or automatic?

**Comment by rael346** [comment]
Added #8 for review. A small PR just to get things going before making some big changes
