### ISSUE TITLE
Remove Scraper Code from sandboxnu/graduatenu

### ISSUE THREAD

**Issue by AlpacaFur** [sandboxnu/major-scraper#7]
## Summary
Since we broke the scraper code out into this repo, it doesn't need to exist in [Graduate's repo](https://github.com/sandboxnu/graduatenu/tree/main/packages/scrapers-v2) any more.

## Tasks
- [ ] Remove the [scrapers-v2](https://github.com/sandboxnu/graduatenu/tree/main/packages/scrapers-v2) package from the repo.
- [ ] Make sure nothing breaks due to its absence
- [ ] Update the README in graduate's repo to link to this repo.
